version: 2.1
orbs:
  node: circleci/node@2.0.2

version: 2.1

workflows:
  matrix-tests:
    jobs:
      - node/test:
          version: 14.9.0
      - node/test:
          version: 12.18.3
      - node/test:
          version: 10.22.0
